# Generated by Django 5.2.6 on 2026-08-08 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticReponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('domaine', models.CharField(choices=[('rh', 'Ressources humaines'), ('projet', 'Gestion de projet'), ('finance', 'Finance & comptabilité'), ('education', 'Éducation & formation'), ('sante', 'Santé'), ('agri', 'Agriculture & agro-industrie'), ('logistique', 'Logistique & transport'), ('communication', 'Communication & marketing'), ('numerique', 'Informatique & numérique'), ('droit', 'Droit & administration'), ('developpement', 'Développement & ONG'), ('autre', 'Autre')], max_length=30)),
                ('domaine_autre', models.CharField(blank=True, default='', max_length=150)),
                ('experience', models.CharField(choices=[('moins5', 'Moins de 5 ans'), ('5a10', '5 à 10 ans'), ('10a20', '10 à 20 ans'), ('plus20', 'Plus de 20 ans')], max_length=20)),
                ('situation', models.CharField(choices=[('poste', 'En poste, salarié(e)'), ('fin_contrat', 'En fin de contrat ou de projet'), ('retraite', 'Proche de la retraite'), ('sans_emploi', 'Sans emploi actuellement'), ('consultant', 'Déjà consultant indépendant')], max_length=20)),
                ('sollicitation', models.CharField(choices=[('souvent', 'Souvent'), ('parfois', 'Quelques fois'), ('jamais', 'Jamais')], max_length=20)),
                ('motivation', models.CharField(choices=[('remuneration', 'Mieux gagner ma vie'), ('independance', "Être indépendant, ne plus dépendre d'un seul employeur"), ('liberte', 'Être plus libre dans mon organisation et mon rythme'), ('valorisation', "Faire payer une expertise que j'ai mis des années à construire"), ('apres_carriere', 'Construire une activité qui dure après ma carrière'), ('impact', 'Avoir un impact réel sur mon secteur'), ('autre', 'Autre')], max_length=30)),
                ('motivation_autre', models.CharField(blank=True, default='', max_length=200)),
                ('a_positionnement', models.BooleanField(default=False)),
                ('a_offre', models.BooleanField(default=False)),
                ('a_tarifs', models.BooleanField(default=False)),
                ('a_prospection', models.BooleanField(default=False)),
                ('difficulte', models.CharField(blank=True, choices=[('reseau', 'Avoir un réseau et des relations'), ('vendre', "Savoir se vendre quand on n'est pas commercial"), ('prix', 'Fixer un prix et le défendre'), ('temps', 'Trouver le temps quand on a déjà un emploi'), ('credibilite', 'Être crédible face à des cabinets établis'), ('autre', 'Autre')], default='', max_length=30)),
                ('difficulte_autre', models.CharField(blank=True, default='', max_length=250)),
                ('anciennete_consultant', models.CharField(blank=True, choices=[('moins1', "Moins d'un an"), ('1a3', '1 à 3 ans'), ('plus3', 'Plus de 3 ans')], default='', max_length=20)),
                ('difficulte_consultant', models.CharField(blank=True, choices=[('missions', 'Trouver des missions régulièrement'), ('tarifs', 'Facturer à leur juste valeur'), ('offre', 'Structurer mon offre'), ('gestion', 'Gérer plusieurs clients en même temps'), ('gros_contrats', 'Passer des petites missions aux gros contrats'), ('autre', 'Autre')], default='', max_length=30)),
                ('difficulte_consultant_autre', models.CharField(blank=True, default='', max_length=250)),
                ('score', models.PositiveSmallIntegerField(default=0, help_text="Nombre d'éléments déjà définis (0 à 4)")),
                ('utm_source', models.CharField(blank=True, default='', max_length=50)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=50)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=100)),
                ('gclid', models.CharField(blank=True, default='', max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('contacte', models.BooleanField(default=False, verbose_name='Contacté en privé')),
                ('ebook_achete', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Réponse au diagnostic',
                'verbose_name_plural': 'Réponses au diagnostic',
                'ordering': ['-date_creation'],
            },
        ),
    ]
