# Generated by Django 5.2.6 on 2025-09-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationwebinaire',
            name='niveau_etude',
            field=models.CharField(blank=True, choices=[('BAC+5', 'BAC+5'), ('BAC+3', 'BAC+3'), ('BAC+7', 'BAC+7'), ('Etudiant', 'Étudiant'), ('Non spécifié', 'Non spécifié')], default='Non spécifié', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reservationwebinaire',
            name='profession',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
