# Generated by Django 5.2.6 on 2025-09-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinaire', '0002_reservationwebinaire_niveau_etude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationwebinaire',
            name='profession',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
