# Generated by Django 5.2.6 on 2025-09-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinaire', '0003_alter_reservationwebinaire_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationwebinaire',
            name='niveau_etude',
            field=models.CharField(blank=True, choices=[('BAC+5', 'BAC+5'), ('BAC+3', 'BAC+3'), ('BAC+7', 'BAC+7'), ('Etudiant', 'Étudiant')], default='Non spécifié', max_length=20, null=True),
        ),
    ]
