# Generated by Django 5.2.6 on 2025-09-29 13:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinaire', '0006_alter_reservationwebinaire_niveau_etude'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('email_name', models.CharField(max_length=100)),
                ('opened', models.BooleanField(default=False)),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('last_opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
