# Generated by Django 5.2.6 on 2025-09-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinaire', '0007_emailtracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationwebinaire',
            name='dans_sequence_opera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservationwebinaire',
            name='niveau_sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
