# Generated by Django 5.2.6 on 2025-09-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinaire', '0008_reservationwebinaire_dans_sequence_opera_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailTracking',
        ),
    ]
