# Generated by Django 5.2.6 on 2026-07-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinaire', '0009_delete_emailtracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationwebinaire',
            name='niveau_etude',
            field=models.CharField(blank=True, choices=[('BAC+5', 'BAC+5'), ('BAC+3', 'BAC+3'), ('BAC+7', 'BAC+8'), ('Etudiant', 'Étudiant'), ('Non spécifié', 'Non spécifié')], default='Non spécifié', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservationwebinaire',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
