# Generated by Django 5.2.6 on 2026-07-18 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinaire', '0010_alter_reservationwebinaire_niveau_etude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationwebinaire',
            name='lien_3h_envoye',
            field=models.BooleanField(default=False),
        ),
    ]
