# Generated by Django 5.2.6 on 2026-07-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinaire', '0011_reservationwebinaire_lien_3h_envoye'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationwebinaire',
            name='gclid',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reservationwebinaire',
            name='utm_campaign',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='reservationwebinaire',
            name='utm_medium',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='reservationwebinaire',
            name='utm_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
