# Generated by Django 5.2.6 on 2026-07-12 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealisationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='realisations/galerie/')),
                ('order', models.PositiveIntegerField(default=1)),
                ('realisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vitrine.realisation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
