# Generated by Django 5.2.6 on 2026-07-13 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('extrait', models.CharField(help_text='Résumé affiché sur la liste des articles (1-2 phrases).', max_length=280)),
                ('contenu', models.TextField(help_text="Corps de l'article. Une ligne vide = un nouveau paragraphe.")),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('auteur', models.CharField(default='Cefiis-IDH', max_length=100)),
                ('temps_lecture', models.CharField(blank=True, help_text="Ex: '5 min'", max_length=20)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='blog.categorie')),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
    ]
