# Generated by Django 5.2.6 on 2026-07-11 20:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EbookAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('prenom', models.CharField(blank=True, default='', max_length=100)),
                ('transaction_id', models.CharField(max_length=120, unique=True)),
                ('montant', models.PositiveIntegerField(default=10000)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('echec', 'Échec')], default='en_attente', max_length=20)),
                ('token_telechargement', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('email_envoye', models.BooleanField(default=False)),
            ],
        ),
    ]
