# Generated by Django 5.2.6 on 2026-07-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EbookPopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default="De l'Expert au Consultant Professionnel", max_length=150)),
                ('pitch', models.TextField(default='Le guide en 5 étapes pour transformer votre expertise en activité de conseil rentable.')),
                ('price_fcfa', models.PositiveIntegerField(default=2000)),
                ('lien_ebook', models.URLField(default='https://ebook.cefiis.com')),
                ('is_active', models.BooleanField(default=True)),
                ('delay_seconds', models.PositiveIntegerField(default=8, help_text='Délai avant apparition du pop-up (secondes)')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, help_text='1 = Initiation, 2 = Avancée, 3 = Professionnalisation')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(help_text='Un paragraphe court, ce que couvre la formation.')),
                ('price_fcfa', models.PositiveIntegerField(help_text='Prix en FCFA, sans espace ni symbole (ex: 50000)')),
                ('duration_label', models.CharField(blank=True, help_text="Ex: '3 semaines', '6 semaines'", max_length=80)),
                ('audience_label', models.CharField(blank=True, help_text="Ex: 'Pour débuter'", max_length=120)),
                ('lien_inscription', models.URLField(help_text="Google Form, page d'inscription, ou lien de paiement — modifiable sans toucher au code.")),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
