# Generated by Django 5.2.6 on 2026-07-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='livrables',
            field=models.TextField(blank=True, help_text="Un livrable concret par ligne — ex: 'Canevas de positionnement'"),
        ),
        migrations.AddField(
            model_name='offer',
            name='prerequis',
            field=models.CharField(blank=True, help_text="Ex: 'Niveau 1 recommandé' — laisser vide pour le niveau 1", max_length=150),
        ),
    ]
