# Generated by Django 5.2.6 on 2026-07-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0002_offer_livrables_offer_prerequis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['categorie', 'order']},
        ),
        migrations.AddField(
            model_name='offer',
            name='categorie',
            field=models.CharField(choices=[('parcours', 'Parcours professionnel (Initiation → Pro)'), ('catalogue', 'Formation ou ressource complémentaire')], default='parcours', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='price_barre_override',
            field=models.PositiveIntegerField(blank=True, help_text='Prix barré personnalisé. Laisser vide pour calcul automatique (x3 du prix actuel).', null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='type_offre',
            field=models.CharField(choices=[('formation', 'Formation'), ('document', 'Modèle / Document à télécharger')], default='formation', max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='audience_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='duration_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='offer',
            name='lien_inscription',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='livrables',
            field=models.TextField(blank=True, help_text='Un livrable par ligne — ignoré pour les documents.'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text="Parcours: 1=Initiation, 2=Avancée, 3=Pro. Catalogue: ordre d'affichage libre."),
        ),
        migrations.AlterField(
            model_name='offer',
            name='prerequis',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price_fcfa',
            field=models.PositiveIntegerField(),
        ),
    ]
