# Generated by Django 5.2.6 on 2026-07-13 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0003_alter_offer_options_offer_categorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InscriptionLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('profession', models.CharField(blank=True, max_length=150)),
                ('diplome', models.CharField(blank=True, max_length=150)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='formations.offer')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
